name: flutter_qyyim
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ****************************************ui控件************************************************************
  # iOS style icons
  cupertino_icons: ^0.1.2
  toast: any
  cached_network_image: ^2.0.0-rc
  pull_to_refresh: ^1.5.7
  flutter_swiper: ^1.1.4
  #富文本
  extended_text_field: ^0.4.9
  extended_text: any
  # webview
  flutter_webview_plugin: "^0.3.11"
  # 预览图片
  # photo_view: ^0.4.2
  #image_picker: ^0.6.3+1
  # 多选图片
  #multi_image_picker: ^4.6.4
  # 多选图片/视频选择，拍照
  image_pickers: ^1.0.7+1
  # 权限管理
  #permission_handler: ^3.1.0
  # 录音插件
  #flutter_plugin_record: ^0.0.9  #The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
  flutter_sound: ^2.1.1
  flutter_audio_recorder: ^0.5.5
  #audioplayers: ^0.14.0
  #拍照 用于自定义录像功能
  camera: ^0.5.7+4
  # 播放视频
  video_player: 0.10.0
  # 红点
  badges: ^1.1.0
  # 启动系统分享
  esys_flutter_share: ^1.0.2
  # 瀑布布局
  flutter_staggered_grid_view: ^0.2.7
  #
  underline_indicator: ^0.0.2
  # 二维码
  qr_flutter: ^3.1.0
  flutter_qr_reader: ^1.0.3
  barcode_scan: 2.0.1
  # 企业级大型应用 路由管理
  fluro: ^1.6.1
  # 闪亮
  shimmer: ^1.0.0
  # 侧滑删除
  flutter_slidable: ^0.5.4
  # 地图
  amap_map_fluttify: ^0.19.1+b2681d9
  amap_search_fluttify: ^0.8.0+b2681d9
  # nestedscroll
  extended_nested_scroll_view: ^0.4.0
  after_layout: ^1.0.7+2
  # 文件选择
  file_picker: ^1.6.2
  #flutter_filereader: ^2.0.0
  open_file: ^3.0.1
  x5_webview: 0.2.0
  # 处理键盘事件
  keyboard_actions: ^3.2.1

  # ****************************数据相关******************************************
  shared_preferences: any
  provider: ^3.0.0+1
  event_bus: ^1.1.1
  sqflite: ^1.2.0
  flutter_screenutil: ^1.0.2
  device_info: ^0.4.0+1
  package_info: ^0.4.0+6
  # 网络相关
  #http: ^0.12.0+1
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  # websocket
  web_socket_channel: ^1.1.0
  # 时间格式
  date_format: "^1.0.4"
  # 获取系统路径
  path_provider: ^1.6.1
  # 生成视频缩略图
  thumbnails:
    git:
      url: https://github.com/divyanshub024/Flutter_Thumbnails.git
  permission_handler: ^5.0.0+hotfix.2
  # 网络检测
  connectivity: ^0.4.8+2
  #^0.23.1 新版和旧版api相差较大
  rxdart: ^0.21.0
  # 轻量级依赖检索容器
  dartin: ^0.1.5
  # json 注解
  json_annotation: ^2.0.0
  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/emoj/
    - assets/data/

    # webp格式的需要手动引入
    - assets/images/tabbar_contacts_c.webp
    - assets/images/tabbar_contacts_s.webp
    - assets/images/tabbar_discover_c.webp
    - assets/images/tabbar_discover_s.webp
    - assets/images/tabbar_chat_c.webp
    - assets/images/tabbar_chat_s.webp
    - assets/images/tabbar_me_c.webp
    - assets/images/tabbar_me_s.webp
    - assets/images/def_avatar.png
    - assets/images/search_black.webp
    - assets/images/search_white.png
    - assets/images/Contact_Female.webp
    - assets/images/Contact_Male.webp
    - assets/images/right_more.png
    - assets/images/favorite.webp
    - assets/images/contacts_add_newmessage.png
    - assets/images/add_addressicon.png
    - assets/images/ic_delete.webp
    - assets/images/ic_right_arrow_black.webp
    - assets/images/ic_right_arrow_grey.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_no_data.webp

    - assets/images/login/select_avatar.webp
    - assets/images/login/ic_select_have.webp
    - assets/images/login/ic_select_have_grey.webp
    - assets/images/login/ic_select_no.png

    - assets/images/chat/ic_Emotion.webp
    - assets/images/chat/ic_Keyboard.webp
    - assets/images/chat/ic_details_add.png
    - assets/images/chat/ic_voice.webp
    - assets/images/chat/ic_chat_more.webp
    - assets/images/chat/ic_chat_voice.webp
    - assets/images/chat/ic_details_camera.webp
    - assets/images/chat/ic_details_card.webp
    - assets/images/chat/ic_details_favorite.webp
    - assets/images/chat/ic_details_file.webp
    - assets/images/chat/ic_details_localtion.webp
    - assets/images/chat/ic_details_media.webp
    - assets/images/chat/ic_details_photo.webp
    - assets/images/chat/ic_details_red.webp
    - assets/images/chat/ic_details_transfer.webp
    - assets/images/chat/ic_details_video.webp
    - assets/images/chat/voice_volume_1.webp
    - assets/images/chat/voice_volume_2.webp
    - assets/images/chat/voice_volume_3.webp
    - assets/images/chat/voice_volume_4.webp
    - assets/images/chat/voice_volume_5.webp
    - assets/images/chat/voice_volume_6.webp
    - assets/images/chat/voice_volume_7.webp
    - assets/images/chat/sound_left_0.webp
    - assets/images/chat/sound_left_1.webp
    - assets/images/chat/sound_left_2.webp
    - assets/images/chat/sound_left_3.webp
    - assets/images/chat/sound_right_0.png
    - assets/images/chat/sound_right_1.webp
    - assets/images/chat/sound_right_2.webp
    - assets/images/chat/sound_right_3.png
    - assets/images/chat/icon_sight_close.png
    - assets/images/chat/flip_camera_icon_nor.webp
    - assets/images/chat/icon_zj.png

    - assets/images/mine/ic_small_code.png
    - assets/images/mine/ic_wallet.webp
    - assets/images/mine/ic_card_package.png
    - assets/images/mine/ic_emoji.png
    - assets/images/mine/ic_pay.png
    - assets/images/mine/ic_setting.png

    - assets/images/contact/ic_contacts_details.png
    - assets/images/contact/ic_no_public.webp
    - assets/images/contact/ic_tag.webp
    - assets/images/contact/ic_group.webp
    - assets/images/contact/ic_new_friend.webp
    - assets/images/contact/ic_video.png
    - assets/images/contact/ic_voice.png
    - assets/images/contact/ic_offical.webp
    - assets/images/contact/ic_reda.webp
    - assets/images/contact/ic_scanqr.webp
    - assets/images/contact/ic_search_wework.webp
    - assets/images/contact/ic_contact_add.webp

    - assets/images/discover/ff_Icon_album.webp
    - assets/images/discover/ff_Icon_shake.webp
    - assets/images/discover/ff_Icon_bottle.webp
    - assets/images/discover/ff_Icon_browse.webp
    - assets/images/discover/ff_Icon_nearby.webp
    - assets/images/discover/ff_Icon_qr_code.webp
    - assets/images/discover/ff_Icon_search.webp
    - assets/images/discover/game_center_h5.webp
    - assets/images/discover/mini_program.webp
    #- assets/pdf.pdf
    #- assets/doc.doc

flutter_intl:
  enabled: true
