name: flutter_qyyim
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^0.1.2
  # 数据相关
  shared_preferences: any
  provider: ^3.0.0+1
  event_bus: ^1.1.1
  sqflite: ^1.2.0
  flutter_screenutil: ^1.0.2

  toast: any
  cached_network_image: any

  # banner
  #flutter_swiper: ^1.1.4
  # 网络相关
  #http: ^0.12.0+1
  dio: ^3.0.9
  #cookie_jar: ^1.0.0

  #permission_handler: ^3.2.0

  #富文本
  extended_text_field: ^0.4.9
  extended_text: any


  # webview
  #flutter_webview_plugin: "^0.3.0+2"
  # 时间格式
  date_format: "^1.0.4"
  # 预览图片
  photo_view: ^0.4.2
  # 图片/视频选择，拍照
  image_picker: ^0.6.3+1
  # 权限管理
  #permission_handler: ^3.1.0
  # 录音插件
  #flutter_plugin_record: ^0.0.9
  flutter_sound: any
  #拍照 用于自定义录像功能
  camera: ^0.5.7+4
  # 播放视频
  video_player: 0.10.0
  # 红点
  badges: ^1.1.0
  # 获取系统路径
  path_provider: ^1.6.1
  # 生成视频缩略图
  thumbnails:
    git:
      url: https://github.com/divyanshub024/Flutter_Thumbnails.git
  # 启动系统分享
  esys_flutter_share: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    #加载页面图片资源
    - images/loading.jpeg

    #底部tab切换图片资源
    - images/contact_list_normal.png
    - images/contact_list_pressed.png
    - images/profile_normal.png
    - images/profile_pressed.png
    - images/message_normal.png
    - images/message_pressed.png

    #菜单按钮
    - images/icon_menu_addfriend.png
    - images/icon_menu_group.png

    #好友模块图标
    - images/icon_addfriend.png
    - images/icon_groupchat.png
    - images/icon_public.png

    #我的模块图标
    - images/icon_me_friends.png
    - images/icon_me_photo.png
    - images/icon_me_file.png
    - images/icon_me_service.png
    - images/icon_me_message.png
    - images/icon_me_clear.png
    - images/code.png
    - images/yixiu.jpeg

    - assets/images/bsc.webp
    - assets/images/bar_close.png
    - assets/images/tabbar_contacts_c.webp
    - assets/images/tabbar_contacts_s.webp
    - assets/images/tabbar_discover_c.webp
    - assets/images/tabbar_discover_s.webp
    - assets/images/tabbar_chat_c.webp
    - assets/images/tabbar_chat_s.webp
    - assets/images/tabbar_me_c.webp
    - assets/images/tabbar_me_s.webp
    - assets/images/def_avatar.png
    - assets/images/search_black.webp
    - assets/images/search_white.png
    - assets/images/Contact_Female.webp
    - assets/images/Contact_Male.webp
    - assets/images/right_more.png
    - assets/images/favorite.webp
    - assets/images/contacts_add_newmessage.png
    - assets/images/add_addressicon.png
    - assets/images/ic_delete.webp
    - assets/images/ic_right_arrow_black.webp
    - assets/images/ic_right_arrow_grey.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_no_data.webp

    - assets/images/login/select_avatar.webp
    - assets/images/login/ic_select_have.webp
    - assets/images/login/ic_select_have_grey.webp
    - assets/images/login/ic_select_no.png

    - assets/images/chat/ic_Emotion.webp
    - assets/images/chat/ic_Keyboard.webp
    - assets/images/chat/ic_details_add.png
    - assets/images/chat/ic_voice.webp
    - assets/images/chat/ic_chat_more.webp
    - assets/images/chat/ic_chat_voice.webp
    - assets/images/chat/ic_details_camera.webp
    - assets/images/chat/ic_details_card.webp
    - assets/images/chat/ic_details_favorite.webp
    - assets/images/chat/ic_details_file.webp
    - assets/images/chat/ic_details_localtion.webp
    - assets/images/chat/ic_details_media.webp
    - assets/images/chat/ic_details_photo.webp
    - assets/images/chat/ic_details_red.webp
    - assets/images/chat/ic_details_transfer.webp
    - assets/images/chat/ic_details_video.webp
    - assets/images/chat/voice_volume_1.webp
    - assets/images/chat/voice_volume_2.webp
    - assets/images/chat/voice_volume_3.webp
    - assets/images/chat/voice_volume_4.webp
    - assets/images/chat/voice_volume_5.webp
    - assets/images/chat/voice_volume_6.webp
    - assets/images/chat/voice_volume_7.webp
    - assets/images/chat/sound_left_0.webp
    - assets/images/chat/sound_left_1.webp
    - assets/images/chat/sound_left_2.webp
    - assets/images/chat/sound_left_3.webp
    - assets/images/chat/sound_right_0.png
    - assets/images/chat/sound_right_1.webp
    - assets/images/chat/sound_right_2.webp
    - assets/images/chat/sound_right_3.png
    - assets/images/chat/icon_sight_close.png
    - assets/images/chat/flip_camera_icon_nor.webp

    - assets/images/mine/ic_small_code.png
    - assets/images/mine/ic_wallet.webp
    - assets/images/mine/ic_card_package.png
    - assets/images/mine/ic_emoji.png
    - assets/images/mine/ic_pay.png
    - assets/images/mine/ic_setting.png

    - assets/images/contact/ic_contacts_details.png
    - assets/images/contact/ic_no_public.webp
    - assets/images/contact/ic_tag.webp
    - assets/images/contact/ic_group.webp
    - assets/images/contact/ic_new_friend.webp
    - assets/images/contact/ic_video.png
    - assets/images/contact/ic_voice.png
    - assets/images/contact/ic_offical.webp
    - assets/images/contact/ic_reda.webp
    - assets/images/contact/ic_scanqr.webp
    - assets/images/contact/ic_search_wework.webp
    - assets/images/contact/ic_contact_add.webp

    - assets/images/discover/ff_Icon_album.webp
    - assets/images/discover/ff_Icon_shake.webp
    - assets/images/discover/ff_Icon_bottle.webp
    - assets/images/discover/ff_Icon_browse.webp
    - assets/images/discover/ff_Icon_nearby.webp
    - assets/images/discover/ff_Icon_qr_code.webp
    - assets/images/discover/ff_Icon_search.webp
    - assets/images/discover/game_center_h5.webp
    - assets/images/discover/mini_program.webp

    - assets/data/friends.json

    - assets/emoj/1.png
    - assets/emoj/2.png
    - assets/emoj/3.png
    - assets/emoj/4.png
    - assets/emoj/5.png
    - assets/emoj/6.png
    - assets/emoj/7.png
    - assets/emoj/8.png
    - assets/emoj/9.png
    - assets/emoj/10.png
    - assets/emoj/11.png
    - assets/emoj/12.png
    - assets/emoj/13.png
    - assets/emoj/14.png
    - assets/emoj/15.png
    - assets/emoj/16.png
    - assets/emoj/17.png
    - assets/emoj/18.png
    - assets/emoj/19.png
    - assets/emoj/20.png
    - assets/emoj/21.png
    - assets/emoj/22.png
    - assets/emoj/23.png
    - assets/emoj/24.png
    - assets/emoj/25.png
    - assets/emoj/26.png
    - assets/emoj/27.png
    - assets/emoj/28.png
    - assets/emoj/29.png
    - assets/emoj/30.png
    - assets/emoj/31.png
    - assets/emoj/32.png
    - assets/emoj/33.png
    - assets/emoj/34.png
    - assets/emoj/35.png
    - assets/emoj/36.png
    - assets/emoj/37.png
    - assets/emoj/38.png
    - assets/emoj/39.png
    - assets/emoj/40.png
    - assets/emoj/41.png
    - assets/emoj/42.png
    - assets/emoj/43.png
    - assets/emoj/44.png
    - assets/emoj/45.png
    - assets/emoj/46.png
    - assets/emoj/47.png
    - assets/emoj/48.png

